from . import category
from . import language
from . import marketplace
from . import offer
from . import product
from . import stock_quant
from . import attribute
from . import partner
from . import res_config_settings
from . import sale_order
from . import sale_order_line
from . import product_pricelist_item
from . import product_field
from . import manufacturer
from . import manufacturer_field
from . import price_list
from . import log